/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutOfficialsRouteImport } from './routes/admin/_layout/officials'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as AdminLayoutCentresRouteImport } from './routes/admin/_layout/centres'
import { Route as AdminLayoutAvailabilityRouteImport } from './routes/admin/_layout/availability'
import { Route as AdminLayoutAppointmentsRouteImport } from './routes/admin/_layout/appointments'
import { Route as AdminLayoutUsersUserIdRouteImport } from './routes/admin/_layout/users/$userId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOfficialsRoute = AdminLayoutOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCentresRoute = AdminLayoutCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAvailabilityRoute = AdminLayoutAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAppointmentsRoute = AdminLayoutAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersUserIdRoute = AdminLayoutUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminLayoutUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/appointments': typeof AdminLayoutAppointmentsRoute
  '/admin/availability': typeof AdminLayoutAvailabilityRoute
  '/admin/centres': typeof AdminLayoutCentresRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/officials': typeof AdminLayoutOfficialsRoute
  '/admin/users': typeof AdminLayoutUsersRouteWithChildren
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/appointments': typeof AdminLayoutAppointmentsRoute
  '/admin/availability': typeof AdminLayoutAvailabilityRoute
  '/admin/centres': typeof AdminLayoutCentresRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/officials': typeof AdminLayoutOfficialsRoute
  '/admin/users': typeof AdminLayoutUsersRouteWithChildren
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_layout/appointments': typeof AdminLayoutAppointmentsRoute
  '/admin/_layout/availability': typeof AdminLayoutAvailabilityRoute
  '/admin/_layout/centres': typeof AdminLayoutCentresRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/officials': typeof AdminLayoutOfficialsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRouteWithChildren
  '/admin/_layout/users/$userId': typeof AdminLayoutUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/verify'
    | '/admin'
    | '/admin/login'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/centres'
    | '/admin/dashboard'
    | '/admin/officials'
    | '/admin/users'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/verify'
    | '/admin'
    | '/admin/login'
    | '/admin/appointments'
    | '/admin/availability'
    | '/admin/centres'
    | '/admin/dashboard'
    | '/admin/officials'
    | '/admin/users'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/verify'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/_layout/appointments'
    | '/admin/_layout/availability'
    | '/admin/_layout/centres'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/officials'
    | '/admin/_layout/users'
    | '/admin/_layout/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BookRoute: typeof BookRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/officials': {
      id: '/admin/_layout/officials'
      path: '/officials'
      fullPath: '/admin/officials'
      preLoaderRoute: typeof AdminLayoutOfficialsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/centres': {
      id: '/admin/_layout/centres'
      path: '/centres'
      fullPath: '/admin/centres'
      preLoaderRoute: typeof AdminLayoutCentresRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/availability': {
      id: '/admin/_layout/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminLayoutAvailabilityRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/appointments': {
      id: '/admin/_layout/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminLayoutAppointmentsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users/$userId': {
      id: '/admin/_layout/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminLayoutUsersUserIdRouteImport
      parentRoute: typeof AdminLayoutUsersRoute
    }
  }
}

interface AdminLayoutUsersRouteChildren {
  AdminLayoutUsersUserIdRoute: typeof AdminLayoutUsersUserIdRoute
}

const AdminLayoutUsersRouteChildren: AdminLayoutUsersRouteChildren = {
  AdminLayoutUsersUserIdRoute: AdminLayoutUsersUserIdRoute,
}

const AdminLayoutUsersRouteWithChildren =
  AdminLayoutUsersRoute._addFileChildren(AdminLayoutUsersRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutAppointmentsRoute: typeof AdminLayoutAppointmentsRoute
  AdminLayoutAvailabilityRoute: typeof AdminLayoutAvailabilityRoute
  AdminLayoutCentresRoute: typeof AdminLayoutCentresRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutOfficialsRoute: typeof AdminLayoutOfficialsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRouteWithChildren
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAppointmentsRoute: AdminLayoutAppointmentsRoute,
  AdminLayoutAvailabilityRoute: AdminLayoutAvailabilityRoute,
  AdminLayoutCentresRoute: AdminLayoutCentresRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutOfficialsRoute: AdminLayoutOfficialsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRouteWithChildren,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BookRoute: BookRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
